### ISSUE TITLE
Pausing and resuming voting periods

### ISSUE THREAD

**Issue by dixonary** [samcoy3/rdan#8]
If votes may be timed, the ability to pause and resume ongoing vote timers may become useful.

The expected syntax would be 

```
!pauseVote v15
```

to pause a particular vote, and
```
!resumeVote v15
```
to resume it.

**Comment by samcoy3** [comment]
Probably won't work on this, at least for now. Not a bad idea but there are some things to think about (what happens when you try to resume a vote which has a fixed end time which you've passed while it's paused, etc).

I might try to work on a `!changevote` or something which lets you modify the end time, though.
